name: Deploy to Okteto
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Okteto
      uses: okteto/login@v1
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate development container
      uses: okteto/deploy-preview@v1
      with:
        name: "my-app-${{ github.run_number }}"
        scope: personal
        timeout: 10m

    - name: Install dependencies
      run: okteto exec -- mvn install

    - name: Deploy to Okteto
      run: okteto exec -- mvn spring-boot:run
