name: Deploy to Okteto

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: username/repo:latest

      - name: Deploy to Okteto
        run: |
          echo "OCTETO_TOKEN=${{ secrets.OCTETO_TOKEN }}" >> $GITHUB_ENV
          curl https://get.okteto.com -sSfL | sh
          okteto version
          okteto namespace
          okteto login -u $OCTETO_TOKEN
          okteto stack deploy -f okteto-stack.yml
        env:
          OCTETO_TOKEN: ${{ secrets.OCTETO_TOKEN }}
